version: "3" 

services:

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

    ports:
      - "5432:5432"
    volumes: 
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  app: 
    build: . 
    command: npm start 
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/app 
    depends_on:
      - db